headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[build]
publish = "C:\\Users\\mitta\\Downloads\\test\\my-portfolio\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\mitta\\Downloads\\test\\my-portfolio"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]